<header>
        
    <nav class="navbar navbar-expand-sm">
        <div class="container">
            
            <a class="navbar-brand" href="/main">
                <img class="img-fluid" src="imagens/twice-logo-branco.png" style="width: 75px">
            </a>

            <button class="navbar-toggler" data-toggle="collapse" data-target="#menu-header">
                <i class="fas fa-hamburger"></i>
            </button>

            <div class="navbar-collapse collapse" id="menu-header">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link nav-a" href="/main">
                            <i class="fas fa-home"></i>
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-a" href="/animes">
                            <i class="fas fa-play-circle"></i>
                            Animes
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-a" href="/filmes">
                            <i class="fas fa-film"></i>
                            Filmes
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-a" href="/config">
                            <i class="fas fa-cog"></i>
                            Configurações
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-a" href="/sair">
                            <i class="fas fa-door-closed"></i>
                            Sair
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

</header>

<section class="main">
        
    <div class="container p-3 mt-3">
        <div class="row mb-4">
            <div class="col-12 d-flex justify-content-center">
                <h1 class="titulo">Episódio <?=$this->view->episodio["numero"]?></h1>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col-12 d-flex justify-content-center">
                <!--<div class="embed-responsive embed-responsive-16by9">
                    <iframe width="560" height="315" src="<?=$this->view->episodio['link']?>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>-->
                <video style="width: 100%;" controls>
                    <source src="videos/One Piece Temporada 13 Episódio 957 Urgente Um Incidente que Afetará os Sete Corsários.mp4" type="video/mp4">
                    
                </video>
            </div>
        </div>
    </div>

</section>