<header>
        
    <nav class="navbar navbar-expand-sm">
        <div class="container">
            
            <a class="navbar-brand" href="/main">
                <img class="img-fluid" src="imagens/twice-logo-branco.png" style="width: 75px">
            </a>

            <button class="navbar-toggler" data-toggle="collapse" data-target="#menu-header">
                <i class="fas fa-hamburger"></i>
            </button>

            <div class="navbar-collapse collapse" id="menu-header">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link nav-a" href="/main">
                            <i class="fas fa-home"></i>
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-a" href="/animes">
                            <i class="fas fa-play-circle"></i>
                            Animes
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-a" href="/filmes">
                            <i class="fas fa-film"></i>
                            Filmes
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-a" href="/config">
                            <i class="fas fa-cog"></i>
                            Configurações
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-a" href="/sair">
                            <i class="fas fa-door-closed"></i>
                            Sair
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

</header>

<section>

    <div class="container mt-3">
        <div class="row mb-3 rounded p-3">
            <?php foreach($this->view->episodios as $episodio) { ?>   
                    <div id="<?=$episodio['id']?>" class="row m-3 rounded p-3 caixa2">
                        <div class="col-12 col-lg-6">
                            <div class="row">
                                <div class="col-12 d-flex text-center justify-content-center">
                                    <h2><?=$this->view->nome_anime." - Episódio <strong>".$episodio['numero']."</strong>"?></h2>
                                </div>
                                <div class="d-flex justify-content-center col-12">
                                    <img src="<?=$episodio['thumb']?>" width="50%">
                                </div>
                            </div>
                            
                        </div>
                        
                        <div class="col-12 col-lg-6 mt-2">
                            <div class="row h-100">
                                <div class="col-12 d-flex text-center align-items-center">
                                    <h3 class=""><?=$episodio["titulo"]?></h3>
                                </div>
                                <div class="col-12 d-flex justify-content-center align-items-end">
                                    <a class="btn btn-dark btn-block btn-ep" href="/assistirEpisodio?id_episodio=<?=$episodio['id']?>&nome_anime=<?=$this->view->nome_anime?>">Assistir</a>
                                </div>
                                <div class="col-12 mt-2 d-flex justify-content-center align-items-end">
                                    <a class="btn btn-dark btn-block btn-ep" href="/editarEpisodio?id_episodio=<?=$episodio['id']?>&nome_anime=<?=$this->view->nome_anime?>">Editar</a>
                                </div>
                            </div>
                                
                            
                        </div>
                    </div>       
            <?php } ?>
        </div>

    </div>

</section>